# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/ui/contatos/contatos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Contatos(object):
    def setupUi(self, Tela_Contatos):
        Tela_Contatos.setObjectName("Tela_Contatos")
        Tela_Contatos.setWindowModality(QtCore.Qt.NonModal)
        Tela_Contatos.setEnabled(True)        
        Tela_Contatos.setMouseTracking(False)
        Tela_Contatos.setFocusPolicy(QtCore.Qt.NoFocus)
        Tela_Contatos.setStyleSheet("QMainWindow{\n"
"background-color: rgb(50,50,50);\n"
"}")
        Tela_Contatos.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        Tela_Contatos.setDocumentMode(False)
        Tela_Contatos.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Tela_Contatos)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 75))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame.setStyleSheet("QFrame {\n"
"background-color: rgb(70,70,70);\n"
"border-radius: 20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.botao_home = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botao_home.sizePolicy().hasHeightForWidth())
        self.botao_home.setSizePolicy(sizePolicy)
        self.botao_home.setStyleSheet("QPushButton{\n"
"icon: url(:/icons/home.svg);\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"icon: url(:/icons/home_hover.svg);\n"
"background-color: transparent;\n"
"}")
        self.botao_home.setText("")
        self.botao_home.setIconSize(QtCore.QSize(40, 40))
        self.botao_home.setObjectName("botao_home")
        self.horizontalLayout.addWidget(self.botao_home)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.botao_contatos = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botao_contatos.sizePolicy().hasHeightForWidth())
        self.botao_contatos.setSizePolicy(sizePolicy)
        self.botao_contatos.setStyleSheet("QPushButton{\n"
"icon: url(:/icons/contatos.svg);\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"icon: url(:/icons/contatos_hover.svg);\n"
"background-color: transparent;\n"
"}")
        self.botao_contatos.setText("")
        self.botao_contatos.setIconSize(QtCore.QSize(40, 40))
        self.botao_contatos.setObjectName("botao_contatos")
        self.horizontalLayout.addWidget(self.botao_contatos)
        spacerItem2 = QtWidgets.QSpacerItem(583, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.botao_conexao = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botao_conexao.sizePolicy().hasHeightForWidth())
        self.botao_conexao.setSizePolicy(sizePolicy)
        self.botao_conexao.setMinimumSize(QtCore.QSize(40, 40))
        self.botao_conexao.setStyleSheet("QPushButton{\n"
"icon: url(:/icons/nao_conectado.svg);\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"icon: url(:/icons/nao_conectado_hover.svg);\n"
"background-color: transparent;\n"
"}")
        self.botao_conexao.setText("")
        self.botao_conexao.setIconSize(QtCore.QSize(35, 35))
        self.botao_conexao.setObjectName("botao_conexao")
        self.horizontalLayout.addWidget(self.botao_conexao)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 500))
        self.frame_2.setStyleSheet("QFrame {\n"
"background-color: rgb(70,70,70);\n"
"border-radius: 20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.frame_2)
        Tela_Contatos.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tela_Contatos)
        QtCore.QMetaObject.connectSlotsByName(Tela_Contatos)

    def retranslateUi(self, Tela_Contatos):
        _translate = QtCore.QCoreApplication.translate
        Tela_Contatos.setWindowTitle(_translate("Tela_Contatos", "API WhatsApp"))
import frontend.ui.contatos.icons_rc as icons_rc
