# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/ui/contatos/adiciona_contatos/adiciona_contatos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Adiciona_Contatos(object):
    def setupUi(self, Adiciona_Contatos):
        Adiciona_Contatos.setObjectName("Adiciona_Contatos")
        Adiciona_Contatos.setEnabled(True)        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Adiciona_Contatos.sizePolicy().hasHeightForWidth())
        Adiciona_Contatos.setSizePolicy(sizePolicy)
        Adiciona_Contatos.setMinimumSize(QtCore.QSize(430, 480))
        Adiciona_Contatos.setMaximumSize(QtCore.QSize(430, 480))
        Adiciona_Contatos.setStyleSheet("QWidget{\n"
"background-color: rgb(50,50,50);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Adiciona_Contatos)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Adiciona_Contatos)
        self.frame.setMinimumSize(QtCore.QSize(0, 75))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame.setStyleSheet("QFrame {\n"
"background-color: rgb(70,70,70);\n"
"border-radius: 20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Adiciona_Contatos)
        self.frame_2.setStyleSheet("QFrame {\n"
"background-color: rgb(70,70,70);\n"
"border-radius: 20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.botao_inserir_planilha = QtWidgets.QPushButton(self.frame_3)
        self.botao_inserir_planilha.setMinimumSize(QtCore.QSize(130, 40))
        self.botao_inserir_planilha.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        self.botao_inserir_planilha.setFont(font)
        self.botao_inserir_planilha.setStyleSheet("QPushButton{\n"
"qproperty-icon: url(:/icons/tabela.svg);\n"
"background-color: rgb(50,50,50);\n"
"color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(90,90,90);\n"
"border-radius:15px;\n"
"}")
        self.botao_inserir_planilha.setIconSize(QtCore.QSize(30, 25))
        self.botao_inserir_planilha.setObjectName("botao_inserir_planilha")
        self.horizontalLayout_2.addWidget(self.botao_inserir_planilha)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.informacoes_planilha = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        self.informacoes_planilha.setFont(font)
        self.informacoes_planilha.setObjectName("informacoes_planilha")
        self.horizontalLayout_2.addWidget(self.informacoes_planilha)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.nome_contato = QtWidgets.QLineEdit(self.frame_4)
        self.nome_contato.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        self.nome_contato.setFont(font)
        self.nome_contato.setStyleSheet("background-color: rgb(60,60,60);\n"
"color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"padding: 10px")
        self.nome_contato.setObjectName("nome_contato")
        self.verticalLayout_3.addWidget(self.nome_contato)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem4)
        self.numero_contato = QtWidgets.QLineEdit(self.frame_4)
        self.numero_contato.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        self.numero_contato.setFont(font)
        self.numero_contato.setStyleSheet("background-color: rgb(60,60,60);\n"
"color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"padding: 10px")
        self.numero_contato.setObjectName("numero_contato")
        self.verticalLayout_3.addWidget(self.numero_contato)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem5)
        self.contato_confianca = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        self.contato_confianca.setFont(font)
        self.contato_confianca.setStyleSheet("QCheckBox{\n"
"color: rgb(255,255,255);\n"
"background-color: transparent\n"
"}")
        self.contato_confianca.setObjectName("contato_confianca")
        self.verticalLayout_3.addWidget(self.contato_confianca)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(121, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.botao_cancelar = QtWidgets.QPushButton(self.frame_5)
        self.botao_cancelar.setEnabled(True)
        self.botao_cancelar.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        self.botao_cancelar.setFont(font)
        self.botao_cancelar.setStyleSheet("QPushButton{\n"
"background-color: rgb(50,50,50);\n"
"color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(90,90,90);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(200,200,200);\n"
"color: rgb(150,150,150);\n"
"}\n"
"")
        self.botao_cancelar.setCheckable(False)
        self.botao_cancelar.setObjectName("botao_cancelar")
        self.horizontalLayout_3.addWidget(self.botao_cancelar)
        self.botao_adicionar = QtWidgets.QPushButton(self.frame_5)
        self.botao_adicionar.setEnabled(False)
        self.botao_adicionar.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        self.botao_adicionar.setFont(font)
        self.botao_adicionar.setStyleSheet("QPushButton{\n"
"background-color: rgb(50,50,50);\n"
"color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(90,90,90);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(200,200,200);\n"
"color: rgb(150,150,150);\n"
"}\n"
"")
        self.botao_adicionar.setCheckable(False)
        self.botao_adicionar.setObjectName("botao_adicionar")
        self.horizontalLayout_3.addWidget(self.botao_adicionar)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Adiciona_Contatos)
        QtCore.QMetaObject.connectSlotsByName(Adiciona_Contatos)

    def retranslateUi(self, Adiciona_Contatos):
        _translate = QtCore.QCoreApplication.translate
        Adiciona_Contatos.setWindowTitle(_translate("Adiciona_Contatos", "Adiciona Contatos"))
        self.label.setText(_translate("Adiciona_Contatos", "<html><head/><body><p><span style=\" color:#ffffff;\">ADICIONA CONTATO</span></p></body></html>"))
        self.botao_inserir_planilha.setText(_translate("Adiciona_Contatos", "PLANILHA"))
        self.informacoes_planilha.setText(_translate("Adiciona_Contatos", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Adiciona_Contatos", "<html><head/><body><p><span style=\" color:#ffffff;\">NOME OU NÚMERO DE TELEFONE</span></p></body></html>"))
        self.nome_contato.setPlaceholderText(_translate("Adiciona_Contatos", "Adicione o nome aqui"))
        self.numero_contato.setPlaceholderText(_translate("Adiciona_Contatos", "Adicione o número aqui"))
        self.contato_confianca.setText(_translate("Adiciona_Contatos", "SALVAR COMO CONTATO DE CONFIANÇA"))
        self.botao_cancelar.setText(_translate("Adiciona_Contatos", "CANCELAR"))
        self.botao_adicionar.setText(_translate("Adiciona_Contatos", "ADICIONAR"))
import frontend.ui.contatos.adiciona_contatos.icons_rc as icons_rc
