# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend\ui\contatos\adiciona_grupos\adiciona_grupos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Adiciona_Grupos(object):
    def setupUi(self, Adiciona_Grupos):
        Adiciona_Grupos.setObjectName("Adiciona_Grupos")
        Adiciona_Grupos.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Adiciona_Grupos.sizePolicy().hasHeightForWidth())
        Adiciona_Grupos.setSizePolicy(sizePolicy)
        Adiciona_Grupos.setMinimumSize(QtCore.QSize(430, 480))
        Adiciona_Grupos.setMaximumSize(QtCore.QSize(430, 480))
        Adiciona_Grupos.setStyleSheet("QWidget{\n"
"background-color: rgb(50,50,50);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Adiciona_Grupos)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Adiciona_Grupos)
        self.frame.setMinimumSize(QtCore.QSize(0, 75))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame.setStyleSheet("QFrame {\n"
"background-color: rgb(70,70,70);\n"
"border-radius: 20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Adiciona_Grupos)
        self.frame_2.setStyleSheet("QFrame {\n"
"background-color: rgb(70,70,70);\n"
"border-radius: 20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.botao_adicionar_contato = QtWidgets.QPushButton(self.frame_6)
        self.botao_adicionar_contato.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        self.botao_adicionar_contato.setFont(font)
        self.botao_adicionar_contato.setStyleSheet("QPushButton{\n"
"icon: url(:/icons/adiciona_contato.svg);\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"icon: url(:/icons/adiciona_contato_hover.svg);\n"
"background-color: transparent;\n"
"}")
        self.botao_adicionar_contato.setText("")
        self.botao_adicionar_contato.setIconSize(QtCore.QSize(40, 40))
        self.botao_adicionar_contato.setObjectName("botao_adicionar_contato")
        self.horizontalLayout_4.addWidget(self.botao_adicionar_contato, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.botao_inserir_planilha = QtWidgets.QPushButton(self.frame_6)
        self.botao_inserir_planilha.setMinimumSize(QtCore.QSize(130, 40))
        self.botao_inserir_planilha.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        self.botao_inserir_planilha.setFont(font)
        self.botao_inserir_planilha.setStyleSheet("QPushButton{\n"
"qproperty-icon: url(:/icons/tabela.svg);\n"
"background-color: rgb(50,50,50);\n"
"color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(90,90,90);\n"
"border-radius:15px;\n"
"}")
        self.botao_inserir_planilha.setIconSize(QtCore.QSize(30, 25))
        self.botao_inserir_planilha.setObjectName("botao_inserir_planilha")
        self.horizontalLayout_4.addWidget(self.botao_inserir_planilha)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem2)
        self.nome = QtWidgets.QLineEdit(self.frame_4)
        self.nome.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        self.nome.setFont(font)
        self.nome.setStyleSheet("background-color: rgb(60,60,60);\n"
"color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"padding: 10px")
        self.nome.setObjectName("nome")
        self.verticalLayout_3.addWidget(self.nome)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(121, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.botao_cancelar = QtWidgets.QPushButton(self.frame_5)
        self.botao_cancelar.setEnabled(True)
        self.botao_cancelar.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        self.botao_cancelar.setFont(font)
        self.botao_cancelar.setStyleSheet("QPushButton{\n"
"background-color: rgb(50,50,50);\n"
"color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(90,90,90);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(200,200,200);\n"
"color: rgb(150,150,150);\n"
"}\n"
"")
        self.botao_cancelar.setCheckable(False)
        self.botao_cancelar.setObjectName("botao_cancelar")
        self.horizontalLayout_3.addWidget(self.botao_cancelar)
        self.botao_adicionar = QtWidgets.QPushButton(self.frame_5)
        self.botao_adicionar.setEnabled(False)
        self.botao_adicionar.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        self.botao_adicionar.setFont(font)
        self.botao_adicionar.setStyleSheet("QPushButton{\n"
"background-color: rgb(50,50,50);\n"
"color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(90,90,90);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(200,200,200);\n"
"color: rgb(150,150,150);\n"
"}\n"
"")
        self.botao_adicionar.setCheckable(False)
        self.botao_adicionar.setObjectName("botao_adicionar")
        self.horizontalLayout_3.addWidget(self.botao_adicionar)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Adiciona_Grupos)
        QtCore.QMetaObject.connectSlotsByName(Adiciona_Grupos)

    def retranslateUi(self, Adiciona_Grupos):
        _translate = QtCore.QCoreApplication.translate
        Adiciona_Grupos.setWindowTitle(_translate("Adiciona_Grupos", "Adiciona Grupos"))
        self.label.setText(_translate("Adiciona_Grupos", "<html><head/><body><p><span style=\" color:#ffffff;\">ADICIONA GRUPO</span></p></body></html>"))
        self.botao_inserir_planilha.setText(_translate("Adiciona_Grupos", "PLANILHA"))
        self.label_2.setText(_translate("Adiciona_Grupos", "<html><head/><body><p><span style=\" color:#ffffff;\">INSIRA O NOME DO GRUPO</span></p></body></html>"))
        self.nome.setPlaceholderText(_translate("Adiciona_Grupos", "Adicione o nome aqui"))
        self.botao_cancelar.setText(_translate("Adiciona_Grupos", "CANCELAR"))
        self.botao_adicionar.setText(_translate("Adiciona_Grupos", "ADICIONAR"))
import frontend.ui.contatos.adiciona_grupos.icons_rc as icons_rc
