# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/ui/tela_principal/adiciona_acao/adiciona_acao.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Adiciona_Acao(object):
    def setupUi(self, Adiciona_Acao):
        Adiciona_Acao.setObjectName("Adiciona_Acao")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Adiciona_Acao.sizePolicy().hasHeightForWidth())
        Adiciona_Acao.setSizePolicy(sizePolicy)
        Adiciona_Acao.setMinimumSize(QtCore.QSize(430, 480))
        Adiciona_Acao.setMaximumSize(QtCore.QSize(430, 480))
        Adiciona_Acao.setStyleSheet("QWidget{\n"
"background-color: rgb(50,50,50);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Adiciona_Acao)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Adiciona_Acao)
        self.frame.setMinimumSize(QtCore.QSize(0, 75))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame.setStyleSheet("QFrame {\n"
"background-color: rgb(70,70,70);\n"
"border-radius: 20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Adiciona_Acao)
        self.frame_2.setStyleSheet("QFrame {\n"
"background-color: rgb(70,70,70);\n"
"border-radius: 20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mensagem = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mensagem.sizePolicy().hasHeightForWidth())
        self.mensagem.setSizePolicy(sizePolicy)
        self.mensagem.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        self.mensagem.setFont(font)
        self.mensagem.setStyleSheet("background-color: rgb(60,60,60);\n"
"color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"padding: 10px")
        self.mensagem.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mensagem.setClearButtonEnabled(False)
        self.mensagem.setObjectName("mensagem")
        self.verticalLayout_3.addWidget(self.mensagem)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(121, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.botao_cancelar = QtWidgets.QPushButton(self.frame_5)
        self.botao_cancelar.setEnabled(True)
        self.botao_cancelar.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        self.botao_cancelar.setFont(font)
        self.botao_cancelar.setStyleSheet("QPushButton{\n"
"background-color: rgb(50,50,50);\n"
"color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(90,90,90);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(200,200,200);\n"
"color: rgb(150,150,150);\n"
"}\n"
"")
        self.botao_cancelar.setCheckable(False)
        self.botao_cancelar.setObjectName("botao_cancelar")
        self.horizontalLayout_3.addWidget(self.botao_cancelar)
        self.botao_adicionar = QtWidgets.QPushButton(self.frame_5)
        self.botao_adicionar.setEnabled(False)
        self.botao_adicionar.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        self.botao_adicionar.setFont(font)
        self.botao_adicionar.setStyleSheet("QPushButton{\n"
"background-color: rgb(50,50,50);\n"
"color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(90,90,90);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(200,200,200);\n"
"color: rgb(150,150,150);\n"
"}\n"
"")
        self.botao_adicionar.setCheckable(False)
        self.botao_adicionar.setObjectName("botao_adicionar")
        self.horizontalLayout_3.addWidget(self.botao_adicionar)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Adiciona_Acao)
        QtCore.QMetaObject.connectSlotsByName(Adiciona_Acao)

    def retranslateUi(self, Adiciona_Acao):
        _translate = QtCore.QCoreApplication.translate
        Adiciona_Acao.setWindowTitle(_translate("Adiciona_Acao", "Adiciona Mensagem"))
        self.label.setText(_translate("Adiciona_Acao", "<html><head/><body><p><span style=\" color:#ffffff;\">ADICIONA MENSAGEM</span></p></body></html>"))
        self.label_2.setText(_translate("Adiciona_Acao", "<html><head/><body><p><span style=\" color:#ffffff;\">INSIRA A MENSAGEM DESEJADA</span></p></body></html>"))
        self.mensagem.setPlaceholderText(_translate("Adiciona_Acao", "Escreva a mensagem aqui"))
        self.botao_cancelar.setText(_translate("Adiciona_Acao", "CANCELAR"))
        self.botao_adicionar.setText(_translate("Adiciona_Acao", "ADICIONAR"))
