# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend\ui\tela_principal\erros\erros.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Erros(object):
    def setupUi(self, Tela_Erros):
        Tela_Erros.setObjectName("Tela_Erros")
        Tela_Erros.setMinimumSize(QtCore.QSize(0, 0))
        Tela_Erros.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Tela_Erros.setStyleSheet("QWidget{\n"
"background-color: rgb(50,50,50);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Tela_Erros)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Tela_Erros)
        self.frame.setMinimumSize(QtCore.QSize(0, 75))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame.setStyleSheet("QFrame {\n"
"background-color: rgb(70,70,70);\n"
"border-radius: 20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Tela_Erros)
        self.frame_2.setStyleSheet("QFrame {\n"
"background-color: rgb(70,70,70);\n"
"border-radius: 20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.erros = QtWidgets.QListWidget(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        self.erros.setFont(font)
        self.erros.setFocusPolicy(QtCore.Qt.NoFocus)
        self.erros.setAutoFillBackground(False)
        self.erros.setStyleSheet("QListWidget {\n"
"    background-color: rgb(70,70,70);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    color: rgb(255,255,255);\n"
"    border-bottom: 1px solid rgb(50,50,50); \n"
"    padding: 10px;   \n"
"}\n"
"\n"
"QListWidget::item:selected{\n"
"    background-color: rgb(80,80,80);\n"
"    border: none;\n"
"    outline: none\n"
"}\n"
"\n"
"\n"
"")
        self.erros.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.erros.setObjectName("erros")
        self.verticalLayout_2.addWidget(self.erros)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Tela_Erros)
        QtCore.QMetaObject.connectSlotsByName(Tela_Erros)

    def retranslateUi(self, Tela_Erros):
        _translate = QtCore.QCoreApplication.translate
        Tela_Erros.setWindowTitle(_translate("Tela_Erros", "Erros"))
        self.label.setText(_translate("Tela_Erros", "<html><head/><body><p><span style=\" color:#ffffff;\">ERROS</span></p></body></html>"))
